### ISSUE TITLE
[Feature]  Pointing to folders instead of files

### ISSUE THREAD

**Issue by costaht** [nwithan8/plex-prerolls#1]
First of all, thanks for keep this project going. 

I'd like to suggest a change where we'd point to a folder instead of files. That will allow the user to just drop files into a folder, let's say "Christmas" and plex-prerolls will automatically pick them up.
That also is gonna make the config file cleaner

Folder structure example:
```
pre-rolls/
├── christmas
├── easter
├── fall
├── halloween
└── independence
```
Thanks

**Comment by nwithan8** [comment]
Unfortunately, Plex doesn't work that way. The preroll list on Plex needs to be [full file paths](https://support.plex.tv/articles/202920803-extras/#:~:text=To%20specify%20a%20pre%2Droll%20video%2C%20simply%20enter%20the%20full%20path%20to%20the%20file%20(e.g.%20/Users/sarah/Movies/preroll.mp4), not just folders.

Thanks for the suggestion though!

**Comment by raph521** [comment]
Apologies if you do not prefer commenting on closed issues, I wasn't sure if it was worth creating a new one of this same feature request.

As a solution to Plex's requirement that full file paths be specified instead of directory paths, could the script `glob`/`ls` the the files in a configured directory and build full file paths with that list, to then be configured as pre-rolls?

For containers, that would just also require that the prerolls directories be mounted with the same directory structure as Plex.

**Comment by nwithan8** [comment]
> For containers, that would just also require that the prerolls directories be mounted with the same directory structure as Plex.

The original proposal is a good one and I considered it, but this ^ popped up as an immediate roadblock. For me personally, I run this container on a completely different system from my Plex server, so there would be no way to pass in the Plex folder path to the system.

I'll see if I can spec something up as perhaps a toggle-able feature.

**Comment by nwithan8** [comment]
Feel free to weigh in on #3 @costaht @raph521 . I'll cut a release soon. Please note, while it worked in initial testing for me, this is considered beta!

**Comment by ThatTallGuy21** [comment]
@costaht @raph521 -- Is this working for you? I posted the below error and I'm having issues with one or more defined paths. Below is the issue I've opened. 

https://github.com/nwithan8/plex-prerolls/issues/4
