### ISSUE TITLE
disable always enable for holidays.

### ISSUE THREAD

**Issue by shedman214** [nwithan8/plex-prerolls#8]
question for the plex pre-roll
I have a pre-roll setup and I'm trying to set up my normal pre-rolls to be removed when special holidays roll around (Halloween, Christmas, etc..._) but re-added after they end. how do I accomplish that? 

Config Link: https://dpaste.org/rHOqq

**Comment by nwithan8** [comment]
Do you have any logs from the most recent run? Should show something like this:
<img width="460" alt="image" src="https://github.com/user-attachments/assets/718a8b2b-8ca6-4ad6-98df-3e59ff3d6448">

**Comment by shedman214** [comment]
[Plex-Prerolls-2024-10-30T22-44-28.log](https://github.com/user-attachments/files/17579799/Plex-Prerolls-2024-10-30T22-44-28.log)
![image](https://github.com/user-attachments/assets/f999e451-b3e3-46b4-9270-d3bcd5f0f318)

**Comment by nwithan8** [comment]
Hmm, I haven't been able to recreate your issue using your config file. Two potential things to try:

1. There is a double quote at [the end of line 113](https://dpaste.org/rHOqq#L113) in your config. For me, the application just completely failed to run with it in there, but it seems yours is running just fine. Copy-paste issue and/or please confirm that this is in fact the config file being used by the application (I will add some logging for this in the future).

2. Which version are you running? Given the "current time matches" log, it would appear the latest v2 version, since that was just added in the most recent release. But please confirm.

**Comment by shedman214** [comment]
I have updated my config.yaml https://dpaste.org/wrWz9
![image](https://github.com/user-attachments/assets/df9478a0-00c4-4670-9d72-4dfeff906aa2)
where would I find what version I'm using?

**Comment by nwithan8** [comment]
> where would I find what version I'm using?

I don't believe it logs it anywhere, it's just based on which Docker tag you're using. If you're using "latest" and have pulled a new container in the past few days, you're using the latest release v2.0.0

**Comment by shedman214** [comment]
ok then i am using the latest release then.

**Comment by nwithan8** [comment]
Alright. Again, I am not able to recreate your issue on my end using your config file. Parsing your config, the application rightly identifies that the Always schedule should be disabled, and only uses the October (10) monthly schedule.

**Comment by nwithan8** [comment]
Any follow-up on this issue?

**Comment by shedman214** [comment]
@nwithan8 it works. my apology for not the update. it works now
